export const seedCars = [
  {
    name: "Aero Sedan",
    price: 48,
    type: "Sedan",
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80",
    seats: 5,
    location: "Dhaka Airport",
    description: "A smooth sedan for airport transfers, office trips, and calm city routes.",
    availability: "Available",
    ownerEmail: "owner1@axleway.com",
    bookingCount: 0
  },
  {
    name: "Metro SUV",
    price: 72,
    type: "SUV",
    image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1200&q=80",
    seats: 7,
    location: "Gulshan",
    description: "A roomy SUV for family plans, weekend drives, and group comfort.",
    availability: "Available",
    ownerEmail: "owner1@axleway.com",
    bookingCount: 0
  },
  {
    name: "City Hatch",
    price: 36,
    type: "Hatchback",
    image: "https://images.unsplash.com/photo-1525609004556-c46c7d6cf023?auto=format&fit=crop&w=1200&q=80",
    seats: 4,
    location: "Dhanmondi",
    description: "A compact hatchback for quick city errands and easy parking.",
    availability: "Unavailable",
    ownerEmail: "owner2@axleway.com",
    bookingCount: 0
  },
  {
    name: "Orbit Electric",
    price: 62,
    type: "Electric",
    image: "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=1200&q=80",
    seats: 5,
    location: "Banani",
    description: "A quiet electric car with clean acceleration and low running cost.",
    availability: "Available",
    ownerEmail: "owner2@axleway.com",
    bookingCount: 0
  },
  {
    name: "Summit Luxury",
    price: 110,
    type: "Luxury",
    image: "https://images.unsplash.com/photo-1523983388277-336a66bf9bcd?auto=format&fit=crop&w=1200&q=80",
    seats: 4,
    location: "Uttara",
    description: "A premium car for business meetings, events, and polished arrivals.",
    availability: "Available",
    ownerEmail: "owner3@axleway.com",
    bookingCount: 0
  },
  {
    name: "Family Microbus",
    price: 88,
    type: "Microbus",
    image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80",
    seats: 10,
    location: "Mirpur",
    description: "A group-friendly microbus for tours, family trips, and team travel.",
    availability: "Unavailable",
    ownerEmail: "owner3@axleway.com",
    bookingCount: 0
  },
  {
    name: "Nova Sedan",
    price: 52,
    type: "Sedan",
    image: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=80",
    seats: 5,
    location: "Mohakhali",
    description: "A balanced sedan with comfortable seating and dependable daily performance.",
    availability: "Available",
    ownerEmail: "owner4@axleway.com",
    bookingCount: 0
  },
  {
    name: "TrailMax SUV",
    price: 82,
    type: "SUV",
    image: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1200&q=80",
    seats: 7,
    location: "Bashundhara",
    description: "A confident SUV for highway routes, luggage-heavy trips, and family rides.",
    availability: "Available",
    ownerEmail: "owner4@axleway.com",
    bookingCount: 0
  },
  {
    name: "Spark Mini",
    price: 32,
    type: "Hatchback",
    image: "https://images.unsplash.com/photo-1493238792000-8113da705763?auto=format&fit=crop&w=1200&q=80",
    seats: 4,
    location: "Badda",
    description: "A simple hatchback for budget-friendly short-distance rentals.",
    availability: "Available",
    ownerEmail: "owner5@axleway.com",
    bookingCount: 0
  },
  {
    name: "Pulse EV",
    price: 68,
    type: "Electric",
    image: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?auto=format&fit=crop&w=1200&q=80",
    seats: 5,
    location: "Niketan",
    description: "An electric rental with a quiet cabin and smooth city handling.",
    availability: "Unavailable",
    ownerEmail: "owner5@axleway.com",
    bookingCount: 0
  },
  {
    name: "Regal Cruiser",
    price: 125,
    type: "Luxury",
    image: "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=1200&q=80",
    seats: 4,
    location: "Baridhara",
    description: "A luxury cruiser for premium events, VIP pickups, and elegant rides.",
    availability: "Available",
    ownerEmail: "owner6@axleway.com",
    bookingCount: 0
  },
  {
    name: "TourLine Microbus",
    price: 95,
    type: "Microbus",
    image: "https://images.unsplash.com/photo-1592198084033-aade902d1aae?auto=format&fit=crop&w=1200&q=80",
    seats: 11,
    location: "Khilgaon",
    description: "A practical microbus for school trips, office groups, and day tours.",
    availability: "Available",
    ownerEmail: "owner6@axleway.com",
    bookingCount: 0
  },
  {
    name: "Civic Route",
    price: 50,
    type: "Sedan",
    image: "https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&w=1200&q=80",
    seats: 5,
    location: "Farmgate",
    description: "A neat sedan for routine commutes, meetings, and flexible pickup plans.",
    availability: "Unavailable",
    ownerEmail: "owner7@axleway.com",
    bookingCount: 0
  },
  {
    name: "Harbor SUV",
    price: 78,
    type: "SUV",
    image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80",
    seats: 7,
    location: "Lalmatia",
    description: "A comfortable SUV with wide cabin space and stable long-route feel.",
    availability: "Available",
    ownerEmail: "owner7@axleway.com",
    bookingCount: 0
  },
  {
    name: "Swift Hatch",
    price: 38,
    type: "Hatchback",
    image: "https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1200&q=80",
    seats: 4,
    location: "Shantinagar",
    description: "A nimble hatchback that keeps city drives light and affordable.",
    availability: "Available",
    ownerEmail: "owner8@axleway.com",
    bookingCount: 0
  },
  {
    name: "Leafline EV",
    price: 64,
    type: "Electric",
    image: "https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=1200&q=80",
    seats: 5,
    location: "Tejgaon",
    description: "An efficient electric car for low-noise rides and cleaner city travel.",
    availability: "Available",
    ownerEmail: "owner8@axleway.com",
    bookingCount: 0
  },
  {
    name: "Velvet Prime",
    price: 135,
    type: "Luxury",
    image: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1200&q=80",
    seats: 4,
    location: "Gulshan 2",
    description: "A premium cabin experience for celebrations, executive travel, and polished plans.",
    availability: "Unavailable",
    ownerEmail: "owner9@axleway.com",
    bookingCount: 0
  },
  {
    name: "CrewWay Microbus",
    price: 92,
    type: "Microbus",
    image: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=1200&q=80",
    seats: 12,
    location: "Jatrabari",
    description: "A roomy microbus for crew movement, airport runs, and group errands.",
    availability: "Available",
    ownerEmail: "owner9@axleway.com",
    bookingCount: 0
  },
  {
    name: "Campus Sedan",
    price: 44,
    type: "Sedan",
    image: "https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=1200&q=80",
    seats: 5,
    location: "Mohammadpur",
    description: "A reliable sedan for university areas, daily errands, and short rental windows.",
    availability: "Available",
    ownerEmail: "owner10@axleway.com",
    bookingCount: 0
  },
  {
    name: "Northstar SUV",
    price: 84,
    type: "SUV",
    image: "https://images.unsplash.com/photo-1504215680853-026ed2a45def?auto=format&fit=crop&w=1200&q=80",
    seats: 7,
    location: "Uttara Sector 7",
    description: "A capable SUV for northern city routes, family pickups, and weekend plans.",
    availability: "Available",
    ownerEmail: "owner10@axleway.com",
    bookingCount: 0
  }
];

